name: Custom Checkout
inputs:
  repo:
    required: true
  ref:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        git init
        git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ inputs.repo }}.git
        git fetch --depth=1 origin ${{ inputs.ref }}
        git checkout FETCH_HEAD